=== dotnet/wpf/src/Microsoft.DotNet.Wpf/src/WpfGfx/codegen/mcg/xml/Elements.xsd
<?xml version="1.0" encoding="utf-8"?>
<!--
 Licensed to the .NET Foundation under one or more agreements.
 The .NET Foundation licenses this file to you under the MIT license.
 See the LICENSE file in the project root for more information.
-->
<xs:schema id="Api" xmlns="" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">

  <!-- "CG" is the root node for the codegen input.  An OutputDirectory property will automatically
        be added and will default to %sdxroot%\wpf -->
  <xs:element name="CG" msdata:IsDataSet="true" msdata:UseCurrentLocale="true">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Elements">
          <xs:complexType>
            <xs:sequence>
              <!-- DataElement corresponds to an elements for which we want
                   to generate a partial class. -->
              <xs:element name="Element" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                  <!-- The name of the element (e.g., "UIElement") -->
                  <xs:attribute name="Name" type="xs:string" />
                  <!-- The namespace in which the element appears (e.g., "System.Windows") -->
                  <xs:attribute name="Namespace" type="xs:string" />
                  <!-- The path where the generator should output the code
                       relative to %sdxroot%\wpf (e.g., "src\Core\CSharp\System\Windows\Generated")
                       This path should end in a "\Generated" subdir by convention. -->
                  <xs:attribute name="ManagedDestinationDir" type="xs:string" />
                  <!-- Whether the element should implement the IAnimatable interface -->
                  <xs:attribute name="ImplementsIAnimatable" type="xs:boolean" />
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="Events">
          <xs:complexType>
            <xs:sequence>
              <!-- DataEvent corresponds to a routed event which should be
                    registered per DataElement. -->
              <xs:element name="Event" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                  <!-- The name of the event less the "Event" suffix (e.g., "MouseLeftButtonDown") -->
                  <xs:attribute name="Name" type="xs:string" />
                  <!-- The type of the event's handler (e.g., "MouseButtonEventHandler") -->
                  <xs:attribute name="HandlerType" type="xs:string" />
                  <!-- If the event should be registered for handled events as well -->
                  <xs:attribute name="HandledToo" type="xs:boolean" />
                  <!-- If we CommandManager.TranslateInput needs to preprocess the event. -->
                  <xs:attribute name="TranslateInput" type="xs:boolean" />
                  <!-- True if the event iinvokes the CommandManager instead of the a virtual on the element instance. -->
                  <xs:attribute name="Commanding" type="xs:boolean" />
                  <!-- A comment describing the event.  Will be displayed in the form "An event reporting ..." -->
                  <xs:attribute name="Comment" type="xs:string" />
                  <!-- An SRID to be used with CustomCategoryAttribute to define the category of the event. (SRID.Example) -->
                  <xs:attribute name="CategoryID" type="xs:string" />
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="Properties">
          <xs:complexType>
            <xs:sequence>
              <!-- DataProperty corresponds to a dependency property which
                   should be registered per DataElement. -->
              <xs:element name="Property" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                  <!-- The name of the property (e.g., "IsMouseOver") -->
                  <xs:attribute name="Name" type="xs:string" />
                  <!-- The type of the property (e.g., "bool") -->
                  <xs:attribute name="Type" type="xs:string" />
                  <!-- The default value of the property (e.g., "BooleanBoxes.FalseBox") -->
                  <xs:attribute name="DefaultValue" type="xs:string" />
                  <!-- True if the property is readonly -->
                  <xs:attribute name="IsReadOnly" type="xs:boolean" />
                  <!-- True if the default changed event (e.g., "IsMouseOverChanged") should be generated for this property. -->
                  <xs:attribute name="ChangedEvent" type="xs:boolean" />
                  <!-- True if this is a reverse inherited property. -->
                  <xs:attribute name="ReverseInherit" type="xs:boolean" />
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== dotnet/wpf/src/Microsoft.DotNet.Wpf/src/WpfGfx/codegen/mcg/xml/Elements.xml
<?xml version="1.0" encoding="utf-8" ?>
<!--
 Licensed to the .NET Foundation under one or more agreements.
 The .NET Foundation licenses this file to you under the MIT license.
 See the LICENSE file in the project root for more information.
-->
<CG xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Elements.xsd">
    <!-- The list of Elements we need to generate partial classes for -->
    <Elements>
        <Element Name="UIElement3D" Namespace="System.Windows" ManagedDestinationDir="src\PresentationCore\System\Windows\Generated" ImplementsIAnimatable="false"/>
        <Element Name="UIElement" Namespace="System.Windows" ManagedDestinationDir="src\PresentationCore\System\Windows\Generated" ImplementsIAnimatable="true"/>
        <Element Name="ContentElement" Namespace="System.Windows" ManagedDestinationDir="src\PresentationCore\System\Windows\Generated" ImplementsIAnimatable="true"/>
    </Elements>

    <!-- The list of Events we need to generate code for per-element -->
    <Events>
        <Event Name="Mouse.PreviewMouseDown" HandlerType="MouseButtonEventHandler" HandledToo="true" Comment="the mouse button was pressed" />
        <Event Name="Mouse.MouseDown" HandlerType="MouseButtonEventHandler" HandledToo="true" TranslateInput="true" Comment="the mouse button was pressed" />
        <Event Name="Mouse.PreviewMouseUp" HandlerType="MouseButtonEventHandler" HandledToo="true" Comment="the mouse button was released" />
        <Event Name="Mouse.MouseUp" HandlerType="MouseButtonEventHandler" HandledToo="true" Comment="the mouse button was released" />

        <!-- Mouse Button Events -->
        <Event Name="UIElement.PreviewMouseLeftButtonDown" HandlerType="MouseButtonEventHandler" Comment="the left mouse button was pressed" />
        <Event Name="UIElement.MouseLeftButtonDown" HandlerType="MouseButtonEventHandler" Comment="the left mouse button was pressed" />
        <Event Name="UIElement.PreviewMouseLeftButtonUp" HandlerType="MouseButtonEventHandler" Comment="the left mouse button was released" />
        <Event Name="UIElement.MouseLeftButtonUp" HandlerType="MouseButtonEventHandler" Comment="the left mouse button was released" />
        <Event Name="UIElement.PreviewMouseRightButtonDown" HandlerType="MouseButtonEventHandler" Comment="the right mouse button was pressed" />
        <Event Name="UIElement.MouseRightButtonDown" HandlerType="MouseButtonEventHandler" Comment="the right mouse button was pressed" />
        <Event Name="UIElement.PreviewMouseRightButtonUp" HandlerType="MouseButtonEventHandler" Comment="the right mouse button was released" />
        <Event Name="UIElement.MouseRightButtonUp" HandlerType="MouseButtonEventHandler" Comment="the right mouse button was released" />

        <!-- Mouse Move Events -->
        <Event Name="Mouse.PreviewMouseMove" HandlerType="MouseEventHandler" Comment="a mouse move" />
        <Event Name="Mouse.MouseMove" HandlerType="MouseEventHandler" Comment="a mouse move" />
        <Event Name="Mouse.PreviewMouseWheel" HandlerType="MouseWheelEventHandler" Comment="a mouse wheel rotation" />
        <Event Name="Mouse.MouseWheel" HandlerType="MouseWheelEventHandler" TranslateInput="true" Comment="a mouse wheel rotation" />
        <Event Name="Mouse.MouseEnter" HandlerType="MouseEventHandler" Comment="the mouse entered this element" />
        <Event Name="Mouse.MouseLeave" HandlerType="MouseEventHandler" Comment="the mouse left this element" />
        <Event Name="Mouse.GotMouseCapture" HandlerType="MouseEventHandler" Comment="that this element got the mouse capture" />
        <Event Name="Mouse.LostMouseCapture" HandlerType="MouseEventHandler" Comment="that this element lost the mouse capture" />
        <Event Name="Mouse.QueryCursor" HandlerType="QueryCursorEventHandler" Comment="the cursor to display was requested" />

        <!-- Styles Events -->
        <Event Name="Stylus.PreviewStylusDown" HandlerType="StylusDownEventHandler" Comment="a stylus-down" />
        <Event Name="Stylus.StylusDown" HandlerType="StylusDownEventHandler" Comment="a stylus-down" />
        <Event Name="Stylus.PreviewStylusUp" HandlerType="StylusEventHandler" Comment="a stylus-up" />
        <Event Name="Stylus.StylusUp" HandlerType="StylusEventHandler" Comment="a stylus-up" />
        <Event Name="Stylus.PreviewStylusMove" HandlerType="StylusEventHandler" Comment="a stylus move" />
        <Event Name="Stylus.StylusMove" HandlerType="StylusEventHandler" Comment="a stylus move" />
        <Event Name="Stylus.PreviewStylusInAirMove" HandlerType="StylusEventHandler" Comment="a stylus-in-air-move" />
        <Event Name="Stylus.StylusInAirMove" HandlerType="StylusEventHandler" Comment="a stylus-in-air-move" />
        <Event Name="Stylus.StylusEnter" HandlerType="StylusEventHandler" Comment="the stylus entered this element" />
        <Event Name="Stylus.StylusLeave" HandlerType="StylusEventHandler" Comment="the stylus left this element" />
        <Event Name="Stylus.PreviewStylusInRange" HandlerType="StylusEventHandler" Comment="the stylus is now in range of the digitizer" />
        <Event Name="Stylus.StylusInRange" HandlerType="StylusEventHandler" Comment="the stylus is now in range of the digitizer" />
        <Event Name="Stylus.PreviewStylusOutOfRange" HandlerType="StylusEventHandler" Comment="the stylus is now out of range of the digitizer" />
        <Event Name="Stylus.StylusOutOfRange" HandlerType="StylusEventHandler" Comment="the stylus is now out of range of the digitizer" />
        <Event Name="Stylus.PreviewStylusSystemGesture" HandlerType="StylusSystemGestureEventHandler" Comment="a stylus system gesture" />
        <Event Name="Stylus.StylusSystemGesture" HandlerType="StylusSystemGestureEventHandler" Comment="a stylus system gesture" />
        <Event Name="Stylus.GotStylusCapture" HandlerType="StylusEventHandler" Comment="that this element got the stylus capture" />
        <Event Name="Stylus.LostStylusCapture" HandlerType="StylusEventHandler" Comment="that this element lost the stylus capture" />
        <Event Name="Stylus.StylusButtonDown" HandlerType="StylusButtonEventHandler" Comment="the stylus button is down" />
        <Event Name="Stylus.StylusButtonUp" HandlerType="StylusButtonEventHandler" Comment="the stylus button is up" />
        <Event Name="Stylus.PreviewStylusButtonDown" HandlerType="StylusButtonEventHandler" Comment="the stylus button is down" />
        <Event Name="Stylus.PreviewStylusButtonUp" HandlerType="StylusButtonEventHandler" Comment="the stylus button is up" />

        <!-- Keyboard Events -->
        <Event Name="Keyboard.PreviewKeyDown" HandlerType="KeyEventHandler" Comment="a key was pressed" />
        <Event Name="Keyboard.KeyDown" HandlerType="KeyEventHandler" TranslateInput="true" Comment="a key was pressed" />
        <Event Name="Keyboard.PreviewKeyUp" HandlerType="KeyEventHandler" Comment="a key was released" />
        <Event Name="Keyboard.KeyUp" HandlerType="KeyEventHandler" Comment="a key was released" />
        <Event Name="Keyboard.PreviewGotKeyboardFocus" HandlerType="KeyboardFocusChangedEventHandler" Comment="that the keyboard is focused on this element" />
        <Event Name="Keyboard.GotKeyboardFocus" HandlerType="KeyboardFocusChangedEventHandler" Comment="that the keyboard is focused on this element" />
        <Event Name="Keyboard.PreviewLostKeyboardFocus" HandlerType="KeyboardFocusChangedEventHandler" Comment="that the keyboard is no longer focusekeyboard is no longer focuseed" />
        <Event Name="Keyboard.LostKeyboardFocus" HandlerType="KeyboardFocusChangedEventHandler" Comment="that the keyboard is no longer focusekeyboard is no longer focuseed" />

        <Event Name="TextCompositionManager.PreviewTextInput" HandlerType="TextCompositionEventHandler" Comment="text composition" />
        <Event Name="TextCompositionManager.TextInput" HandlerType="TextCompositionEventHandler" Comment="text composition" />

        <!-- Commanding Events -->
        <Event Name="CommandManager.PreviewExecuted" HandlerType="ExecutedRoutedEventHandler" Commanding="true" />
        <Event Name="CommandManager.Executed" HandlerType="ExecutedRoutedEventHandler" Commanding="true" />
        <Event Name="CommandManager.PreviewCanExecute" HandlerType="CanExecuteRoutedEventHandler" Commanding="true" />
        <Event Name="CommandManager.CanExecute" HandlerType="CanExecuteRoutedEventHandler" Commanding="true" />
        <Event Name="CommandDevice.CommandDevice" HandlerType="CommandDeviceEventHandler" Commanding="true" />

        <!-- Drag/Drop Events -->
        <Event Name="DragDrop.PreviewQueryContinueDrag" HandlerType="QueryContinueDragEventHandler" Comment="the preview query continue drag is going to happen" />
        <Event Name="DragDrop.QueryContinueDrag" HandlerType="QueryContinueDragEventHandler" Comment="the query continue drag is going to happen" />
        <Event Name="DragDrop.PreviewGiveFeedback" HandlerType="GiveFeedbackEventHandler" Comment="the preview give feedback is going to happen" />
        <Event Name="DragDrop.GiveFeedback" HandlerType="GiveFeedbackEventHandler" Comment="the give feedback is going to happen" />
        
        <Event Name="DragDrop.PreviewDragEnter" HandlerType="DragEventHandler" Comment="the preview drag enter is going to happen" />
        <Event Name="DragDrop.DragEnter" HandlerType="DragEventHandler" Comment="the drag enter is going to happen" />
        <Event Name="DragDrop.PreviewDragOver" HandlerType="DragEventHandler" Comment="the preview drag over is going to happen" />
        <Event Name="DragDrop.DragOver" HandlerType="DragEventHandler" Comment="the drag over is going to happen" />
        <Event Name="DragDrop.PreviewDragLeave" HandlerType="DragEventHandler" Comment="the preview drag leave is going to happen" />
        <Event Name="DragDrop.DragLeave" HandlerType="DragEventHandler" Comment="the drag leave is going to happen" />
